name: Laravel CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3
        timeout: 600s

    env:
      APP_KEY: base64:Vbbz48G5EBU/AOR0SNyi+fkEsIZY/io7JbMAWlUj/cU=
      DB_PASSWORD: root@admin

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, pdo, mysql

    - name: Install dependencies
      run: composer install --prefer-dist --no-ansi --no-interaction --no-scripts --no-progress

    - name: Copy .env
      run: cp .env.example .env

    - name: Set environment variables in .env
      run: |
        echo "APP_KEY=base64:Vbbz48G5EBU/AOR0SNyi+fkEsIZY/io7JbMAWlUj/cU=" >> .env
        echo "DB_PASSWORD=root@admin" >> .env

    - name: Generate application key
      run: php artisan key:generate

    - name: Run migrations
      run: php artisan migrate

    - name: Run tests
      run: php artisan test
